<a href="https://colab.research.google.com/github/Haroun-corp/neural-colab-lab/blob/main/learn_neural_main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello IA !")

Hello IA !


In [3]:
import numpy as np

# Créer des données
donnees = np.array([1, 2, 3, 4, 5])

print("Données :", donnees)
print("Moyenne :", np.mean(donnees))
print("Somme :", np.sum(donnees))

Données : [1 2 3 4 5]
Moyenne : 3.0
Somme : 15


In [4]:
image = np.array([
    [0, 128, 255],
    [64, 100, 200],
    [30, 75, 180]
])

print("Image :\n", image)
print("Taille :", image.shape)
print("Pixel le plus lumineux :", np.max(image))
print("Pixel le plus sombre :", np.min(image))


Image :
 [[  0 128 255]
 [ 64 100 200]
 [ 30  75 180]]
Taille : (3, 3)
Pixel le plus lumineux : 255
Pixel le plus sombre : 0


In [5]:
# Convertir du texte en nombres
texte = "bonjour"
encoded = [ord(lettre) for lettre in texte]
print("Texte :", texte)
print("Encodé :", encoded)

# Reconvertir en texte
decoded = ''.join([chr(n) for n in encoded])
print("Décodé :", decoded)


Texte : bonjour
Encodé : [98, 111, 110, 106, 111, 117, 114]
Décodé : bonjour


Exercice : Mon premier neurone
Instructeur Claude Sonnet 4.6


In [7]:
import numpy as np

# Les entrées (par exemple des caractéristiques d'un texte)
entrees = np.array([0.5, 0.3, 0.8])

# Les poids (initialisés au hassard au début)
poids = np.array([0.4, 0.7, 0.2])

# Le biais (un ajustement supplémentaire)
biais = 0.1

# Le calcul du neurone
sortie = np.sum(entrees * poids) + biais

print("Entrées :", entrees)
print("Poids :", poids)
print("Sortie du neurone :", sortie)

# Ajouter une fonction d'activation
def relu(x):
  return np.maximum(0, x)

sortie_activee = relu(sortie)
print("Après ReLU :", sortie_activee)

Entrées : [0.5 0.3 0.8]
Poids : [0.4 0.7 0.2]
Sortie du neurone : 0.67
Après ReLU : 0.67


Exercice: Un neurone qui apprend

In [8]:
import numpy as np

# Le vrai résultat qu'on veut (doubler l'entrée)
X = np.array([1, 2, 3, 4, 5], dtype=float)
Y = np.array([2, 4, 6, 8, 10], dtype=float)

# poids initial (au hasard)
poids = 0.0
learning_rate = 0.01

# Entrainement sur 100 essais
for epoch in range(100):
  # Prédiction
  prediction = X * poids

  # Calcul de l'erreur
  erreur = prediction - Y

  # Correction du poids
  gradient = np.mean(erreur * X)
  poids = poids - learning_rate * gradient

  if epoch % 10 == 0:
    print(f"Epoch {epoch} | Poids: {poids:.4f} | Erreur moyenne: {np.mean(erreur**2):.4f}")

  print(f"\nPoids final : {poids:.4f} (devrait être proche de 2.0)")

Epoch 0 | Poids: 0.2200 | Erreur moyenne: 44.0000

Poids final : 0.2200 (devrait être proche de 2.0)

Poids final : 0.4158 (devrait être proche de 2.0)

Poids final : 0.5901 (devrait être proche de 2.0)

Poids final : 0.7452 (devrait être proche de 2.0)

Poids final : 0.8832 (devrait être proche de 2.0)

Poids final : 1.0060 (devrait être proche de 2.0)

Poids final : 1.1154 (devrait être proche de 2.0)

Poids final : 1.2127 (devrait être proche de 2.0)

Poids final : 1.2993 (devrait être proche de 2.0)

Poids final : 1.3764 (devrait être proche de 2.0)
Epoch 10 | Poids: 1.4450 | Erreur moyenne: 4.2781

Poids final : 1.4450 (devrait être proche de 2.0)

Poids final : 1.5060 (devrait être proche de 2.0)

Poids final : 1.5604 (devrait être proche de 2.0)

Poids final : 1.6087 (devrait être proche de 2.0)

Poids final : 1.6518 (devrait être proche de 2.0)

Poids final : 1.6901 (devrait être proche de 2.0)

Poids final : 1.7242 (devrait être proche de 2.0)

Poids final : 1.7545 (devrait êt

Récap de ce que j'ai compris jusqu'ici
.Les données = des tableau de nombres
.Un neurone = multiplication + addition + activation
.Apprendre = corriger les poids en minimisant l'erreur


In [3]:
import torch
import torch.nn as nn

# Données : nombres de 0 à 9
X = torch.tensor([
    [0.], [1.], [2.], [3.], [4.],
    [5.], [6.], [7.], [8.], [9.]
])

# Labels : 0 = pair, i = impair
Y = torch.tensor([
    [0.], [1.], [0.], [1.], [0.],
    [1.], [0.], [1.], [0.], [1.]
])

# Le réseau de neurones
model = nn.Sequential(
    nn.Linear(1, 8),    # Couche 1: 1 entrée -> 8 neurones
    nn.ReLU(),          # Activation
    nn.Linear(8, 1),    # Couche 2 : neurones -> 1 sortie
    nn.Sigmoid()        # Sortie entre 0 et 1
)

# Fonction de perte et optimiseur
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# entraînement
for epoch in range(1000):
  prediction = model(X)
  loss = criterion(prediction, Y)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch % 200 == 0:
    print(f"epoch {epoch} | Perte: {loss.item():.4f}")

# Test
print("\n--- Test ---")
for i in range(10):
  pred = model(torch.tensor([[float(i)]]))
  print(f"{i} -> {'Impair' if pred.item() > 0.5 else 'Pair'}")


epoch 0 | Perte: 0.7482
epoch 200 | Perte: 0.6100
epoch 400 | Perte: 0.5513
epoch 600 | Perte: 0.5396
epoch 800 | Perte: 0.5373

--- Test ---
0 -> Pair
1 -> Impair
2 -> Pair
3 -> Pair
4 -> Pair
5 -> Pair
6 -> Impair
7 -> Impair
8 -> Impair
9 -> Impair


Le modèle n'a pas bien appris 3, 5 sont classé Pair alors qu'ils sont impairs
Le problème c'est que pair/impair n'est pas une relation linéaire avec le chiffre lui-même. Le réseau a du mal à trouver le pattern
On va l'aider en lui donnant une melleiure répresentation -- le modulo 2(le reste de la division par 2)

In [6]:
import torch
import torch.nn as nn

# Astuce : on donne le modulo comme feature suplémentaire
X = torch.tensor([
    [0., 0.], [1., 1.], [2., 0.], [3., 1.], [4., 0.],
    [5., 1.], [6., 0.], [7., 1.], [8., 0.], [9., 1.]
])

# Labels : 0 = pair, i = impair
Y = torch.tensor([
    [0.], [1.], [0.], [1.], [0.],
    [1.], [0.], [1.], [0.], [1.]
])

# Le réseau de neurones
model = nn.Sequential(
    nn.Linear(2, 8),    # Couche 1: 1 entrée -> 8 neurones
    nn.ReLU(),          # Activation
    nn.Linear(8, 1),    # Couche 2 : neurones -> 1 sortie
    nn.Sigmoid()        # Sortie entre 0 et 1
)

# Fonction de perte et optimiseur
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# Entraînement
for epoch in range(1000):
  prediction = model(X)
  loss = criterion(prediction, Y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch % 200 == 0:
    print(f"Epoch {epoch} | Perte: {loss.item():.4f}")

# Test
print("\n--- Test ---")
for i in range(10):
  inp = torch.tensor([[float(i), float(i % 2)]])
  pred = model(inp)
  print(f"{i} -> {'Impair' if pred.item() > 0.5 else 'Pair'}")


Epoch 0 | Perte: 0.9709
Epoch 200 | Perte: 0.0158
Epoch 400 | Perte: 0.0026
Epoch 600 | Perte: 0.0010
Epoch 800 | Perte: 0.0006

--- Test ---
0 -> Pair
1 -> Impair
2 -> Pair
3 -> Impair
4 -> Pair
5 -> Impair
6 -> Pair
7 -> Impair
8 -> Pair
9 -> Impair
